const PRODUCTS = [
  {
    name: 'Namdev Chiwada',
    namMarathi: 'नामदेव चिवडा',
    slug: 'namdev-chiwada',
    sub: 'House Signature Blend',
    intro: 'Slow-roasted with pure ghee & hand-ground Solapur masala.',
    desc: 'Our legendary chiwda — slow-roasted with pure ghee, curry leaves & hand-ground Solapur masala. Six generations of perfection in every bite.',
    category: 'mild',
    tag: '🏆 Most Loved',
    badge: 'Bestseller',
    badgeColor: '#e07000',
    price: 180,
    originalPrice: 210,
    weight: '250g',
    img: 'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077912/chiwada-1_lzpu9p.jpg',
    images: [
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077911/chiwada-2_dcpktr.jpg',
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776078023/chiwada-3_mkertz.jpg',
      
    ],
    sizes: [
      { weight: '250g', price: 180 },
      { weight: '500g', price: 340 },
      { weight: '1kg',  price: 640 },
    ],
    ingredients: ['Thick Poha','Mustard Seeds','Curry Leaves','Green Chili','Peanuts','Cashew','Turmeric','Rock Salt','Sugar','Ghee'],
    nutrition: [['Serving Size','30g'],['Calories','128 kcal'],['Total Fat','5.8g'],['Carbohydrates','17g'],['Protein','3.2g'],['Sodium','145mg']],
    info: 'Shelf life: 45 days. No artificial colors. Pure cow ghee used. 100% Vegetarian.',
    rating: 4.9,
    reviews: 284,
    featured: true,
    sortOrder: 1,
  },
  {
    name: 'Bakarvadi',
    namMarathi: 'बाकरवडी',
    slug: 'bakarvadi',
    sub: 'Spiced Pastry Rolls',
    intro: 'Crispy spiral rolls with spiced coconut-sesame filling.',
    desc: 'Pune-style spiral pastry rolls stuffed with spiced coconut-sesame filling, deep-fried to golden perfection. A timeless Maharashtrian classic.',
    category: 'spicy',
    tag: '✨ Chef\'s Pick',
    badge: 'Premium',
    badgeColor: '#d4af37',
    price: 200,
    originalPrice: 230,
    weight: '250g',
    img: 'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077912/bakarwadi-1_pgklui.jpg',
    images: [
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077912/bakarwadi-2_ln3slo.jpg',
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776078319/WhatsApp_Image_2025-10-12_at_09.55.44_8c57616c_h7rddn.jpg',
    ],
    sizes: [
      { weight: '250g', price: 200 },
      { weight: '500g', price: 380 },
    ],
    ingredients: ['Refined Flour','Coconut','Sesame Seeds','Poppy Seeds','Tamarind','Jaggery','Red Chili','Coriander','Fennel'],
    nutrition: [['Serving Size','30g'],['Calories','158 kcal'],['Total Fat','8.9g'],['Carbohydrates','17g'],['Protein','3.1g'],['Sodium','160mg']],
    info: 'Shelf life: 30 days. Best consumed fresh. 100% Vegetarian.',
    rating: 4.8,
    reviews: 218,
    featured: true,
    sortOrder: 2,
  },
  {
    name: 'Maka Chiwada',
    namMarathi: 'मका चिवडा',
    slug: 'maka-chiwada',
    sub: 'Corn Flakes Chiwada',
    intro: 'Extra crispy corn chiwada with bold Kolhapuri masala.',
    desc: 'Crispy corn flakes chiwada spiced with bold Kolhapuri masala. A fiery treat loved by spice enthusiasts across Maharashtra.',
    category: 'spicy',
    tag: '🌶️ Hot Pick',
    badge: '🔥 Spicy',
    badgeColor: '#dc2626',
    price: 130,
    originalPrice: 155,
    weight: '200g',
    img: 'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077911/maka-chiwada-1_eqxer1.jpg',
    images: [
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077911/maka-chiwada-2_zsispw.jpg',
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776078321/WhatsApp_Image_2025-10-12_at_09.54.18_d8c26e7d_qd4cq0.jpg',
    ],
    sizes: [
      { weight: '200g', price: 130 },
      { weight: '500g', price: 300 },
    ],
    ingredients: ['Corn Flakes','Kolhapuri Masala','Peanuts','Red Chili','Garlic','Mustard Oil','Rock Salt','Curry Leaves'],
    nutrition: [['Serving Size','30g'],['Calories','138 kcal'],['Total Fat','6.5g'],['Carbohydrates','18g'],['Protein','3.8g'],['Sodium','195mg']],
    info: 'Shelf life: 45 days. High spice level. Not recommended for children. 100% Vegetarian.',
    rating: 4.7,
    reviews: 156,
    featured: true,
    sortOrder: 3,
  },
  {
    name: 'Special Farsan',
    namMarathi: 'स्पेशल फरसाण',
    slug: 'special-farsan',
    sub: 'Premium Festive Mix',
    intro: 'Festive mix of sev, peanuts & chana dal in house masala.',
    desc: 'A festive mix of crispy sev, roasted peanuts, fried chana dal & poha flakes tossed in our signature house masala. Celebratory in every handful.',
    category: 'special',
    tag: '🎉 Festive Fave',
    badge: 'New',
    badgeColor: '#2d5a1b',
    price: 160,
    originalPrice: 185,
    weight: '250g',
    img: 'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077912/farsan-1_l0qoob.jpg',
    images: [
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776077911/farsan-2_qgwjxl.jpg',
      'https://res.cloudinary.com/dz7ykg6qr/image/upload/v1776078734/surti-farsan_30417_ony0jr.jpg',
    ],
    sizes: [
      { weight: '250g', price: 160 },
      { weight: '500g', price: 300 },
    ],
    ingredients: ['Besan Sev','Roasted Peanuts','Fried Chana Dal','Poha Flakes','Mustard Oil','Red Chili','Rock Salt','Curry Leaves'],
    nutrition: [['Serving Size','30g'],['Calories','142 kcal'],['Total Fat','7.2g'],['Carbohydrates','16g'],['Protein','5.3g'],['Sodium','180mg']],
    info: 'Shelf life: 60 days. No preservatives. 100% Vegetarian.',
    rating: 4.6,
    reviews: 98,
    featured: true,
    sortOrder: 4,
  },
];

module.exports = PRODUCTS;